services:
  pomich-app:
    build: .
    container_name: pomich-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - pomich-data:/app/data
    restart: unless-stopped

volumes:
  pomich-data:
